name: flutter_app_scaffold
description: A new Flutter application.

# アプリバージョン
# [メジャーバージョン].[マイナーバージョン].[パッチバージョン]+[ビルド番号]
#
# - ストアでバージョン x.y.z+* を審査に提出済みのとき、次にアップロードするバージョンは x.y.(z+1)+*
# - ストアにバージョン x.y.z+a をアップロード済みのとき、次にアップロードするバージョンは x.y.z+(a+1)
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

  # 次の一行を記述するとビルドに使用する flutter sdk version を指定できる
  # Note: ビルドに使用する flutter sdk version は flutter version コマンドで選択できる
  # FIXME: flutter version コマンド実行時も次に1行にひっかかり失敗してしまうので、flutter version 実行時のみコメントアウトする
  flutter: 1.19.0-0.0.pre

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 標準で使えるアイコンセット
  cupertino_icons: ^0.1.3

  # StateNotifierを使って状態管理したい
  # https://pub.dev/packages/state_notifier
  state_notifier: ^0.4.0

  # StateNotifierをWidgetTree上で保持したい
  # https://pub.dev/packages/flutter_state_notifier
  flutter_state_notifier: ^0.4.2

  # InheritedWidgetを利用した状態管理を楽に行いたい
  # https://pub.dev/packages/provider
  provider: ^4.1.1

  # StatelessWidgetの中でもTabControllerやAnimationControllerを生成したい
  # https://pub.dev/packages/vsync_provider
  vsync_provider: ^0.4.1

  # RxOperatorを使いたい
  # https://pub.dev/packages/rxdart
  rxdart: ^0.24.0

  # 複雑なRoutingを楽に書きたい
  # https://pub.dev/packages/fluro
  fluro: ^1.6.3

  # いい感じのローディング表示をしたい
  # https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^4.1.2+1

  # デバイス情報を取得したい
  # https://pub.dev/packages/device_info#-installing-tab-
  device_info: ^0.4.2+4

  # アプリバージョンとかを取得したい
  # https://pub.dev/packages/package_info#-installing-tab-
  package_info: ^0.4.0+18

  # string.Formatしたい
  # https://pub.dev/packages/sprintf
  sprintf: ^4.0.2

  # URLを外部ブラウザで開きたい
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.4.7

  # Textの文字サイズを自動で調整したい
  auto_size_text: ^2.1.0

  # アプリアイコンを楽に設定したい
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.7.5

  # Googleの用意したフォントを使用したい（デフォルトのフォントは中華っぽさがあって格好悪い）
  # https://pub.dev/packages/google_fonts
  google_fonts: ^1.1.0

  # Tupleを使いたい
  # https://pub.dev/packages/tuple
  tuple: ^1.0.3

  # Http通信したい
  # https://pub.dev/packages/http
  http: ^0.12.1

  # アプリのローカルストレージに値を保存したい
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/